-f $ENV_CSTR_DIR_PRJ/source/xkcalcnel/fetcher/calc_fth_top_inc.f
-f $ENV_CSTR_DIR_PRJ/source/xkcalc/kernel/adder/calc_add_top_inc.f
-f $ENV_CSTR_DIR_PRJ/source/xkcalc/kernel/substrator/calc_sub_top_inc.f
-f $ENV_CSTR_DIR_PRJ/source/xkcalc/kernel/multiplier/calc_mul_top_inc.f
-f $ENV_CSTR_DIR_PRJ/source/xkcalc/kernel/divider/calc_div_top_inc.f
-f $ENV_CSTR_DIR_PRJ/source/xkcalc/kernel/dumper/calc_dmp_top_inc.f
