.EXPORT_ALL_VARIABLES:
CSTR_TOP      = calc_add_knl
CSTR_INC      = $(ENV_CSTR_DIR_PRJ)/source/xkcalc/kernel/adder/calc_add_top_inc.f
CSTR_LIB      = $(ENV_CSTR_DIR_PRJ)/source/xkcalc/kernel/adder/calc_add_top_lib.f
CSTR_RTL      = $(ENV_CSTR_DIR_PRJ)/source/xkcalc/kernel/adder/calc_add_top_rtl.f
DATA_PRD_CLK ?= 10.000

include ../script/makefile.mk
