.EXPORT_ALL_VARIABLES:
CSTR_TOP          = calc_add_knl
CSTR_INC          = $(ENV_CSTR_DIR_PRJ)/source/xkcalc/kernel/adder/calc_add_top_inc.f
CSTR_LIB          = $(ENV_CSTR_DIR_PRJ)/source/xkcalc/kernel/adder/calc_add_top_lib.f
CSTR_RTL          = $(ENV_CSTR_DIR_PRJ)/source/xkcalc/kernel/adder/calc_add_top_rtl.f
CSTR_LEVEL_WAIVE ?= both

include ../script/makefile.mk
