.EXPORT_ALL_VARIABLES:
SHELL   := /bin/csh

ENV_CSTR_DIR_PRJ := ../..

SYN_TOP := enc_top
SYN_TAR ?= xczu9eg-ffvb1156-2L-e

SIM_TOP ?= sim_$(SYN_TOP)

STP_LVL ?= local

SEED    ?= 0

include ../vv_script/makefile.mk
